### ISSUE TITLE
Allow CSS and JavaScript Code to be Rendered

### ISSUE THREAD

**Issue by mkarimshahbaz** [nsia-infosys/stat.gov.af#17]
Currently, we are only able to add HTML code as a widget in the text box, but we can't add CSS and JavaScript codes to be rendered in dashboards. For better look of dashboards we should allow both CSS and JavaScript codes to be rendered in dashboards so that we can add styling and animations.

**Comment by hpardess** [comment]
@mkarimshahbaz Please test the task.
Open database and add value in (widgets.text) table for text widget.
example: 

> test dashbaord
> <p style="color: red;">bold and red text</p>
> <script>alert("good job")</script>
