### ISSUE TITLE
Translate dashboard names into Pashto and Dari languages

### ISSUE THREAD

**Issue by mkarimshahbaz** [nsia-infosys/stat.gov.af#23]
We can name dashboards with simple JS objects e.g. { en:"dashboard_name_en", dr :"dashboard_name_dari", ps:"dashboard_name_pashto" }. Then, we can load related language text base on keys.

**Comment by hpardess** [comment]
The json should be like this:
{"ps": "سالنامه ۲۰۱۸ - ۲۰۱۹", "dr":"سالنامه ۲۰۱۸ - ۲۰۱۹", "en": "Statistical Yearbook 2018-19"}
