### ISSUE TITLE
Translate visualization names into Pashto and Dari languages

### ISSUE THREAD

**Issue by mkarimshahbaz** [nsia-infosys/stat.gov.af#24]
We can name visualizations with a simple JS object e.g. { en:"visualization_name_en", dr :"visualization_name_dari", ps:"visualization_name_pashto" }. Then, we can load related language text base on language keys.

**Comment by hpardess** [comment]
- We cannot use single-quotes around properties, like 'foo'.  JSON.parse("{'foo': 1}");

The json should be like this: {"ps": "Pashto", "dr":"Dari", "en": "Government employees Eng"}
